version: "3.8"
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always
    user: "100:101"