version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@devnexuslab.me"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin123"  # Change this to a secure password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"  # PgAdmin web interface
    restart: always

volumes:
  pgadmin_data:
