version: "3.8"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl
      - ./file:/vault/file
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      SKIP_SETCAP: "true"
    cap_add:
      - IPC_LOCK
    command: server
    ports:
      - "8200:8200"
    restart: always
