version: "3.8"
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:16.4.12
    container_name: teleport
    volumes:
      - ./teleport.yaml:/etc/teleport/teleport.yaml
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    restart: always